src_c/circle.c

Fixes circle initialization, previously values passed to __init__ were ignored.
Fixed argument type passed in _pg_circle_set_radius.

Circle init fix

---

geometry.pyi
src_c/Include/circle.h
src_c/Include/collisions.h
src_c/circle.c
unittests/circle_test.py

This PR does many things:
- Adds a first batch of unit tests for the Circle type.
- Fixes a problem we had with getters not raising TypeError on wrong type.
- Adds the Circle type to the geometry.pyi file
- Added path for single item sequences in pgCircle_FromObject
- Circle no longer supports negative radius creation and assignment

Add Circle unit tests, added to .pyi and other

---

.github/workflows/ubuntu_test.yml
.github/workflows/windows_test.yml

Previously all workflow names were `Unit Test`, now they are called:
- `Ubuntu latest` for Ubuntu
- `Windows latest` for Windows

Updated GH workflow names to reflect OS name

---

benchmarks/GEOMETRY_circle_benchmark.py
src_c/circle.c
test/test_circle.py

The `circle.collideswith()` function didn't have support for Circle-Line collision and had a wrong behaviour for unsupported types, so i added support for the Line type and corrected the wrong behaviour. I also added more benchmarks and the missing collideswith() unittests.

Add line support to collideswith

---

src_c/circle.c

Made code clearer, more compact and in line with the line implementation (pun not intended).
After discussions on discord we decided to remove the (circle only) functionality to support a single argument in move/move_ip. This is no longer a thing.

Update move(), move_ip() to be same with the line implementation

---

README.md

Function did not allow black circles as it would `set_colorkey` on it. This way the surface starts off transparent.

Support black color in `get_new_circle_surf`

---

src_c/circle.c
src_c/include/base.h
src_c/line.c
src_c/polygon.c

This PR adds 3 new C api functions for creating tuples representing points. It also implements part of these functions to existing API (specifically the line one) to make them safer and more compact.
- **pg_TupleFromDoubles**
Takes two doubles and returns a tuple containing two PyFloat objects on success, NULL and sets an error otherwise
- **pg_TupleFromInts** 
Same as the last but for ints
- **pg_PointList_FromArrayDouble**
Takes an even length double array and returns a list of points: 
`C_arr[1, 2, 3, 4, 5, 6, 7, 8] -> List((1, 2), (3, 4), (5, 6), (7, 8))`
- **pg_PointTuple_FromArrayDouble**
Takes an even length double array and returns a tupleof points: 
`C_arr[1, 2, 3, 4, 5, 6, 7, 8] -> Tuple((1, 2), (3, 4), (5, 6), (7, 8))`
- line `a` getter
The getter was unsafe as it directly set …

Add new functions for safe and fast tuple generation

---

setup.py

this script allows this format:
`python setup.py --format --test <rest-of-the-build-options>`

improved `setup.py`

---

benchmarks/GEOMETRY_polygon_benchmark.py
src_c/polygon.c

This PR adds some more polygon benchmarks and a new function that improves performance for the polygon move functions and for any future function that returns a copy of the original polygon with updated vertices.
This is because of the fact that in those kinds of functions we allocate new memory that we use for vertices manipulation already, so it doesn't make sense to create new memory again and discard the other. All of this saves an extra memory allocation and a memcpy, saving about 20-25%.

New polygon creation method

---

src_c/circle.c
test/test_circle.py

Before this PR you could do:
```Python
circle = Circle((10, 10), 4)
circle.r = 0
circle.d = 0
circle.circumference = 0
circle.area = 0
```
This is no more.
Another issue this PR tries to solve is attribute assignment error messages. These were very imprecise and did not distinguish between a wrong type being passed and  a wrong value. It now raises `TypeError` on wrong type and `ValueError` on wrong value ( <= 0 ).

Disallowed degenerate(radius=0) circles + better error messages

---

src_c/geometry.c
test/test_polygon.py

I've found a little optimization due to the fact that `pgPolygonNew2` utilizes `_pg_polygon_subtype_new2`. The latter has the peculiarity to allocate new memory, copy from the input one and also has to calculate the center of the polygon, therefore having to run trough a for loop for all the vertices.
With this optimization i basically skip new memory assigment (like in `_pg_polygon_subtype_new2_transfer`) by directly assigning the already available memory and i also skip the whole memcpy step and pymemfree. I also easily skip the "running trough all the verticies" as we already know where the center of the poly should be because it's the values we passed as params to the function. 
I've also swapped all ints for Py_ssize_t(s) as it's more scalable this way and makes this work on all …

geometry.regular_polygon() optimization

---

src_c/circle.c
src_c/include/base.h
src_c/line.c
src_c/polygon.c

This should address a comment from @Emc2356 in #128. This PR swaps all occurrences of two doubles extraction from the fastcall args with a common inline function. I tested with and without the inline and i noticed that the inline keeps performance way closer to the original, though a touch (approx 1%) slower. This should make our code shorter and more readable and maintainable over time.

Added pg_TwoDoublesFromFastcallArgs and swapped all duplicates

---

CONTRIBUTING.md

I have only provided the build guide for Debian-based Linux distributions. Others could perhaps submit PRs for other families of distributions.

Add Linux build guide in `CONTRIBUTING.md`

---

src_c/line.c

We were wasting a lot of performance by not having line.colliderect() FASTCALL. With this i see a 36% performance improvement overall.
The results:
OLD:
```
COLLISION: RECT
==================================================
|             Name             |  Total  |  Mean  |  Std Dev  |
|------------------------------|---------|--------|-----------|
|            C rect            | 590.56  | 59.06  |   1.15    |
|           NC rect            | 610.32  | 61.03  |    2.5    |
|         inside rect          |  587.4  | 58.74  |   0.91    |
|           C 4 int            | 1260.65 | 126.06 |   2.64    |
|           NC 4 int           | 1255.34 | 125.53 |   1.54    |
|         inside 4 int         | 1251.77 | 125.18 |   1.01    |
|          C 4 float           | 1131.43 | 113.14 |   2.04    | …
```

Made line.colliderect() FASTCALL

---

src_c/circle.c
src_c/geometry.c
src_c/include/geometry.h
src_c/line.c
src_c/polygon.c
test/test_line.py

I consolidated all PI-related defines in the geometry.h header to reduce duplication in the poly, circle, and line modules. I also standardized the naming conventions and made necessary fixes and refactoring to support the changes. The changes I made include:
- Using "M_" to prefix all PI-related constants (e.g. `M_PI`, `M_TWOPI`)
- Replacing `DEG_TO_RAD` and `RAD_TO_DEG` macros with static inline functions
- Adding new constants: `M_PI_QUO_4` (PI / 4), `M_PI_QUO_180` (PI / 180), and `M_180_QUO_PI` (180 / PI)
- Correcting a test
- Updating all PI-related references to use the new constants and functions

moved all PI related constants to geometry.h

---

benchmarks/GEOMETRY_polygon_benchmark.py
src_c/polygon.c
test/test_polygon.py

**Changes:**
- Revisions to the move and move_ip functions to make them more efficient
- Changes to the rotate functions to improve their implementation
- Removed unnecessary center recalculation in the move function (O(N) to O(1))
- Optimized vertices movement calculation by separating cases of movement into x-y, x-0, and 0-y
- Made move and move_ip of (0, 0) O(1) by adding a check and exiting early
- Added more tests and expanded the benchmark suite
- 44.5% improvement in total suite test time for move and move_ip
- deleted `_pg_polygon_subtype_new2_transfer` function
**Results:**
OLD
```
MOVE
==================================================
|    Name     |  Total  |  Mean  |  Std Dev  |
|-------------|---------|--------|-----------|
|  int (x-x)  | 2930.6  | 293.06 |   2.49    |
| …
```

Polygon `move()/move_ip()` optimization

---

src_c/collisions.c
src_c/simd_collisions.h
src_c/simd_collisions_avx2.c

This PR implements a runtime check on whether the AVX2 instruction set is present or not in the CPU. Compile-time macros like `__AVX2__` only flags whether the compiler support generating code using AVX2, but not whether the running system would be able to execute it. If a non-AVX2-supporting processor runs an AVX2-using code, the program will generate a segfault over an unrecognized instruction/opcode, as what I intend to fix #202. Because pygame-geometry doesn't use SDL2, which means not being able to use the straightforward `SDL_HasAVX2` function, I had to make my own function to check it.

Implement runtime check for AVX2 SIMD functionality in collisions

---

docs/circle.rst
docs/line.rst
geometry.pyi
src_c/circle.c
src_c/line.c
test/test_circle.py
test/test_line.py

Now both Circle and Line's `collideswith` method will accept polygons. This PR also corrects line collidepolygon tests and adds new ones to accommodate for the changes. It comes with a caveat that is the collideswith method will only work as if the "only_edges" param were set to False. This is because for now collideswith is intended to be a function with a single argument so i had to enforce one behaviour.

Added polygon to Circle and Line collideswith

---

docs/circle.rst
docs/geometry.rst
geometry.pyi
src_c/circle.c
test/test_circle.py

Add Circle `top`, `left`, `right`, `bottom` attributes

---

src_c/line.c
test/test_line.py

```Py
from geometry import Line
import pygame
def main():
pygame.init()
line = Line((100, 100), (700, 700))
screen = pygame.display.set_mode((800, 800))
clock = pygame.time.Clock()
keep = True
clicked = False
rot_point = line.center
while keep:
dt = clock.tick_busy_loop(60)
if clicked:
line.rotate_ip(dt, rot_point)
screen.fill((0, 0, 0))
pygame.draw.line(screen, (255, 255, 255), line.a, line.b)
pygame.draw.circle(screen, (255, 0, 0), rot_point, 5)
pygame.display.flip()
for event in pygame.event.get():
if event.type == pygame.QUIT:
keep = False
elif event.type == pygame.MOUSEBUTTONDOWN:
clicked = True
elif event.type == pygame.MOUSEBUTTONUP:
clicked = False
if event.button == 3:
rot_point = event.pos
if __name__ == "__main__":
main()
```

Fix line rotate
